name: Test

on:
  push:
  #  branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lingo-db/hipy-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          echo "deb http://deb.debian.org/debian trixie main" > /etc/apt/sources.list.d/trixie.list
          printf 'Package: *\nPin: release n=bookworm\nPin-Priority: 900\n\nPackage: *\nPin: release n=trixie\nPin-Priority: 100\n' > /etc/apt/preferences.d/pin-trixie
          apt update && apt install -y ccache lld
          apt install -y -t trixie gcc-13 g++-13
          echo "CC=gcc-13" >> $GITHUB_ENV
          echo "CXX=g++-13" >> $GITHUB_ENV
          python3 -m venv ${{ github.workspace }}/venv
          echo "${{ github.workspace }}/venv/bin" >> $GITHUB_PATH
          source ${{ github.workspace }}/venv/bin/activate
          pip install pytest pytest-cov pytest-xdist numpy pandas pyarrow networkx scipy pybind11 jinja2 scikit-learn typeshed_client
          python -c "import pyarrow; pyarrow.create_library_symlinks()"

      - name: Run tests
        shell: bash
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          export PYTHONPATH=".:$PYTHONPATH"
          pytest test -n auto --cov=hipy --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
